[[compose.greeter.services]]
imago = "services/rpc-greeter/imago.toml"

[[compose.client.services]]
imago = "services/cli-client/imago.toml"

[profile.greeter]
config = "greeter"

[profile.client]
config = "client"

[target.alice]
remote = "ssh://imagod-alice?socket=/run/imago/imagod.sock"

[target.bob]
remote = "ssh://imagod-bob?socket=/run/imago/imagod.sock"
