"$schema" = "https://raw.githubusercontent.com/yieldspace/imago/main/schemas/imago.schema.json"

name.cargo = true

main = "target/release/wasm32-wasip2/example-service.wasm"
type = "cli"

[capabilities]
wasi = true

[target.default]
remote = "ssh://localhost?socket=/run/imago/imagod.sock"
