#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE' >&2
Usage: .github/scripts/verify_plugin_wkg_locks.sh [plugin-dir]

Checks that every plugin under plugins/* with wit/package.wit has a committed
wkg.lock that matches lock content generated by `wkg wit build`.
USAGE
}

if (($# > 1)); then
  usage
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PLUGINS_ROOT="${REPO_ROOT}/plugins"

if [[ ! -d "${PLUGINS_ROOT}" ]]; then
  echo "error: plugins directory was not found: ${PLUGINS_ROOT}" >&2
  exit 1
fi

if ! command -v wkg >/dev/null 2>&1; then
  echo "error: wkg command is required but was not found in PATH" >&2
  exit 1
fi

declare -a plugin_dirs=()
if (($# == 1)); then
  plugin_name="$1"
  if [[ "${plugin_name}" == *"/"* || "${plugin_name}" == "." || "${plugin_name}" == ".." ]]; then
    echo "error: invalid plugin dir argument: ${plugin_name}" >&2
    exit 2
  fi
  plugin_path="${PLUGINS_ROOT}/${plugin_name}"
  if [[ ! -d "${plugin_path}" ]]; then
    echo "error: plugin directory does not exist: ${plugin_path}" >&2
    exit 1
  fi
  plugin_dirs=("${plugin_path}")
else
  while IFS= read -r dir; do
    plugin_dirs+=("${dir}")
  done < <(find "${PLUGINS_ROOT}" -mindepth 1 -maxdepth 1 -type d | sort)
fi

if ((${#plugin_dirs[@]} == 0)); then
  echo "error: no plugin directories found under ${PLUGINS_ROOT}" >&2
  exit 1
fi

checked=0
failures=0

for plugin_dir in "${plugin_dirs[@]}"; do
  plugin_name="$(basename "${plugin_dir}")"
  wit_package="${plugin_dir}/wit/package.wit"

  if [[ ! -f "${wit_package}" ]]; then
    if (($# == 1)); then
      echo "error: ${plugin_name} does not contain wit/package.wit" >&2
      exit 1
    fi
    continue
  fi

  lock_file="${plugin_dir}/wkg.lock"
  if [[ ! -f "${lock_file}" ]]; then
    echo "error: missing lock file: ${lock_file}" >&2
    failures=$((failures + 1))
    continue
  fi

  checked=$((checked + 1))
  temp_root="$(mktemp -d)"
  build_log="${temp_root}/wkg-build.log"

  cp -R "${plugin_dir}/wit" "${temp_root}/wit"
  if ! (
    cd "${temp_root}"
    wkg wit build >"${build_log}" 2>&1
  ); then
    echo "error: failed to run 'wkg wit build' for ${plugin_name}" >&2
    sed -n '1,120p' "${build_log}" >&2 || true
    rm -rf "${temp_root}"
    failures=$((failures + 1))
    continue
  fi

  generated_lock="${temp_root}/wkg.lock"
  if [[ ! -f "${generated_lock}" ]]; then
    echo "error: build did not produce wkg.lock for ${plugin_name}" >&2
    rm -rf "${temp_root}"
    failures=$((failures + 1))
    continue
  fi

  if ! diff -u "${lock_file}" "${generated_lock}" >/dev/null; then
    echo "error: ${lock_file} is out of date. Run: (cd plugins/${plugin_name} && wkg wit build)" >&2
    diff -u "${lock_file}" "${generated_lock}" >&2 || true
    rm -rf "${temp_root}"
    failures=$((failures + 1))
    continue
  fi

  rm -rf "${temp_root}"
done

if ((checked == 0)); then
  echo "error: no plugin with wit/package.wit was found" >&2
  exit 1
fi

if ((failures > 0)); then
  echo "wkg.lock verification failed for ${failures} plugin(s)." >&2
  exit 1
fi

echo "wkg.lock verification passed for ${checked} plugin(s)."
