[workspace]
release = false
release_always = false
publish = false
git_only = false
git_tag_enable = false
git_release_enable = false
git_release_type = "pre"
changelog_update = true
pr_labels = ["release"]

[[package]]
name = "imago-cli"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = true
git_tag_name = "imago-v{{ version }}"
git_release_name = "imago-v{{ version }}"
version_group = "imago-cli"
git_release_body = """
## CLI Release

{{ changelog }}
"""

[[package]]
name = "imagod"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = true
git_tag_name = "imagod-v{{ version }}"
git_release_name = "imagod-v{{ version }}"
version_group = "imagod-daemon"
git_release_body = """
## Daemon Release

{{ changelog }}
"""

[[package]]
name = "imago-protocol"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imago-shared"

[[package]]
name = "imago-plugin-macros"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-common"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-config"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-control"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-ipc"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-runtime"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-runtime-bootstrap"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-runtime-control"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-runtime-ingress"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-runtime-internal"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-runtime-wasmtime"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imagod-server"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imago-plugin-imago-admin"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imago-plugin-imago-experimental-gpio"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imago-plugin-imago-experimental-i2c"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imago-plugin-imago-node"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"

[[package]]
name = "imago-plugin-imago-usb"
release = true
publish = false
git_only = true
git_tag_enable = true
git_release_enable = false
changelog_update = false
version_group = "imagod-daemon"
