name = "local-imagod-plugin-native-admin-app"
main = "target/wasm32-wasip2/release/local-imagod-plugin-native-admin-app.wasm"
type = "cli"

[build]
command = "CARGO_TARGET_DIR=target cargo build --target wasm32-wasip2 --release"

[[dependencies]]
version = "0.1.0"
kind = "native"
path = "../../plugins/imago-admin/wit"

[capabilities]
privileged = true
wasi = true

[capabilities.deps]
"imago:admin" = ["*"]

[target.default]
remote = "ssh://localhost?socket=/tmp/imagod-local-plugin-native-admin.sock"
