listen_addr = "127.0.0.1:4443"
storage_root = ".imagod-data"
server_version = "imagod/local-plugin-native-admin-example"
compatibility_date = "2026-02-10"

[tls]
server_key = "certs/server.key"
client_public_keys = ["cd89018994ede35b4c80b21d7958a4a6fc2684637846f6938175b0a87ccc9ff3"]

[runtime]
chunk_size = 1048576
max_inflight_chunks = 16
upload_session_ttl_secs = 900
stop_grace_timeout_secs = 30
runner_ready_timeout_secs = 3
runner_log_buffer_bytes = 262144
epoch_tick_interval_ms = 50
