#[path = "e2e_helper/mod.rs"]
mod e2e_helper;

use e2e_helper::TestResult;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Output, Stdio};
use std::thread;
use std::time::{Duration, Instant};
use tempfile::Builder as TempDirBuilder;

const DEFAULT_TIMEOUT: Duration = Duration::from_secs(120);
const CLIENT_PUBLIC_KEY_SAMPLE: &str =
    "1111111111111111111111111111111111111111111111111111111111111111";

#[derive(Debug)]
struct RunResult {
    stdout: String,
    stderr: String,
    combined: String,
    status: String,
    timed_out: bool,
}

#[test]
#[ignore]
fn e2e_imagod_creates_default_config_when_missing() -> TestResult {
    let temp = TempDirBuilder::new().prefix("iecfgm").tempdir()?;
    let config_path = temp.path().join("imagod.toml");
    assert!(
        !config_path.exists(),
        "config must be missing before run: {}",
        config_path.display()
    );

    let run = run_imagod_with_timeout(&config_path, DEFAULT_TIMEOUT)?;

    assert!(
        config_path.exists(),
        "imagod.toml was not created: {}",
        render_run_result(&run)
    );
    assert!(
        run.combined.contains("imagod created default config at"),
        "default-config creation log was not found: {}",
        render_run_result(&run)
    );
    assert!(
        !run.combined.contains("config read failed"),
        "unexpected config read failure was found: {}",
        render_run_result(&run)
    );

    let generated = fs::read_to_string(&config_path)?;
    assert!(
        generated.contains("# This file was autogenerated by imagod."),
        "generated config is missing autogenerated comment: {}",
        generated
    );
    assert!(
        generated
            .contains("# Review tls.server_key and tls.client_public_keys before production use."),
        "generated config is missing review comment: {}",
        generated
    );
    assert!(
        generated
            .contains("# Add peer public keys to tls.client_public_keys to allow RPC clients."),
        "generated config is missing peer key comment: {}",
        generated
    );
    assert!(
        generated.contains("listen_addr = "),
        "generated config is missing listen_addr: {}",
        generated
    );
    assert!(
        generated.contains("server_version = "),
        "generated config is missing server_version: {}",
        generated
    );
    assert!(
        generated.contains("compatibility_date = "),
        "generated config is missing compatibility_date: {}",
        generated
    );
    assert!(
        generated.contains("[tls]"),
        "generated config is missing [tls]: {}",
        generated
    );
    assert!(
        generated.contains("server_key = "),
        "generated config is missing tls.server_key: {}",
        generated
    );
    assert!(
        generated.contains("client_public_keys = "),
        "generated config is missing tls.client_public_keys: {}",
        generated
    );
    assert!(
        generated.contains("client_public_keys = []"),
        "generated config should contain empty tls.client_public_keys: {}",
        generated
    );
    let server_key_path = extract_toml_string_value(&generated, "server_key")
        .map(PathBuf::from)
        .expect("generated config should include tls.server_key as string");
    assert!(
        server_key_path.is_absolute(),
        "generated tls.server_key should be absolute: {}",
        server_key_path.display()
    );
    assert!(
        server_key_path.exists(),
        "generated server key file does not exist: {}",
        server_key_path.display()
    );
    let server_key = fs::read_to_string(&server_key_path)?;
    assert!(
        server_key.contains("BEGIN PRIVATE KEY"),
        "generated server key is not PEM private key: {}",
        server_key
    );
    assert!(
        !generated.contains("storage_root = "),
        "generated config unexpectedly contains storage_root: {}",
        generated
    );
    assert!(
        !generated.contains("[runtime]"),
        "generated config unexpectedly contains [runtime]: {}",
        generated
    );

    Ok(())
}

#[test]
#[ignore]
fn e2e_imagod_does_not_overwrite_existing_config() -> TestResult {
    let temp = TempDirBuilder::new().prefix("iecfgo").tempdir()?;
    let config_path = temp.path().join("imagod.toml");
    let storage_root = temp.path().join("storage-root");
    let server_key = temp.path().join("server.key");
    let existing = format!(
        "listen_addr = \"127.0.0.1:0\"\nstorage_root = \"{}\"\nserver_version = \"imagod/existing\"\ncompatibility_date = \"2026-02-10\"\n\n[tls]\nserver_key = \"{}\"\nclient_public_keys = [\"{}\"]\n",
        toml_escape(storage_root.to_string_lossy().as_ref()),
        toml_escape(server_key.to_string_lossy().as_ref()),
        CLIENT_PUBLIC_KEY_SAMPLE,
    );
    fs::write(&config_path, &existing)?;
    let before = fs::read_to_string(&config_path)?;

    let run = run_imagod_with_timeout(&config_path, DEFAULT_TIMEOUT)?;
    let after = fs::read_to_string(&config_path)?;

    assert_eq!(
        after,
        before,
        "existing config was overwritten: {}",
        render_run_result(&run)
    );
    assert!(
        !run.combined.contains("imagod created default config at"),
        "unexpected default-config creation log was found: {}",
        render_run_result(&run)
    );

    Ok(())
}

fn run_imagod_with_timeout(config_path: &Path, timeout: Duration) -> TestResult<RunResult> {
    let workspace_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let child = Command::new("cargo")
        .arg("run")
        .arg("--quiet")
        .arg("--manifest-path")
        .arg(workspace_root.join("Cargo.toml"))
        .arg("-p")
        .arg("imagod")
        .arg("--")
        .arg("--config")
        .arg(config_path)
        .current_dir(&workspace_root)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()?;
    let (output, timed_out) = wait_or_kill(child, timeout)?;

    let stdout = String::from_utf8_lossy(&output.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
    let combined = format!("{stdout}{stderr}");

    Ok(RunResult {
        stdout,
        stderr,
        combined,
        status: output.status.to_string(),
        timed_out,
    })
}

fn wait_or_kill(mut child: Child, timeout: Duration) -> TestResult<(Output, bool)> {
    let deadline = Instant::now() + timeout;
    loop {
        if child.try_wait()?.is_some() {
            return Ok((child.wait_with_output()?, false));
        }
        if Instant::now() >= deadline {
            let _ = child.kill();
            return Ok((child.wait_with_output()?, true));
        }
        thread::sleep(Duration::from_millis(100));
    }
}

fn render_run_result(run: &RunResult) -> String {
    format!(
        "status={}, timed_out={}, stdout={}, stderr={}",
        run.status, run.timed_out, run.stdout, run.stderr
    )
}

fn toml_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn extract_toml_string_value(content: &str, key: &str) -> Option<String> {
    let prefix = format!("{key} = \"");
    content.lines().find_map(|line| {
        let trimmed = line.trim();
        let rest = trimmed.strip_prefix(&prefix)?;
        let value = rest.strip_suffix('"')?;
        Some(value.replace("\\\\", "\\").replace("\\\"", "\""))
    })
}
