#[path = "e2e_helper/mod.rs"]
mod e2e_helper;

use e2e_helper::TestResult;
use e2e_helper::binaries::resolve_imagod_binary;
use e2e_helper::certs::generate_key_material;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::thread;
use std::time::{Duration, Instant};
use tempfile::Builder as TempDirBuilder;

const DEFAULT_TIMEOUT: Duration = Duration::from_secs(15);
const CLIENT_PUBLIC_KEY_SAMPLE: &str =
    "1111111111111111111111111111111111111111111111111111111111111111";

#[derive(Debug, Clone, Copy)]
enum ReadinessMode {
    DefaultConfigCreated,
    Listening,
}

#[derive(Debug)]
struct RunResult {
    stdout: String,
    stderr: String,
    combined: String,
    status: String,
    timed_out: bool,
}

#[test]
#[ignore]
fn e2e_imagod_creates_default_config_when_missing() -> TestResult {
    let temp = TempDirBuilder::new()
        .prefix("iecfgm")
        .tempdir_in(std::env::temp_dir())?;
    let config_path = temp.path().join("imagod.toml");
    assert!(
        !config_path.exists(),
        "config must be missing before run: {}",
        config_path.display()
    );

    let run = run_imagod_until_ready(
        &config_path,
        DEFAULT_TIMEOUT,
        ReadinessMode::DefaultConfigCreated,
    )?;

    assert!(
        config_path.exists(),
        "imagod.toml was not created: {}",
        render_run_result(&run)
    );
    assert!(
        run.combined.contains("imagod created default config at"),
        "default-config creation log was not found: {}",
        render_run_result(&run)
    );
    assert!(
        !run.timed_out,
        "imagod startup timed out unexpectedly: {}",
        render_run_result(&run)
    );
    assert!(
        !run.combined.contains("config read failed"),
        "unexpected config read failure was found: {}",
        render_run_result(&run)
    );

    let generated = fs::read_to_string(&config_path)?;
    assert!(
        generated.contains("# This file was autogenerated by imagod."),
        "generated config is missing autogenerated comment: {}",
        generated
    );
    assert!(
        generated
            .contains("# Review tls.server_key and tls.client_public_keys before production use."),
        "generated config is missing review comment: {}",
        generated
    );
    assert!(
        generated
            .contains("# Add peer public keys to tls.client_public_keys to allow RPC clients."),
        "generated config is missing peer key comment: {}",
        generated
    );
    assert!(
        generated.contains(
            "\"$schema\" = \"https://raw.githubusercontent.com/yieldspace/imago/main/schemas/imagod.schema.json\""
        ),
        "generated config is missing $schema URL: {}",
        generated
    );
    assert!(
        generated.contains("listen_addr = "),
        "generated config is missing listen_addr: {}",
        generated
    );
    assert!(
        generated.contains("control_socket_path = "),
        "generated config is missing control_socket_path: {}",
        generated
    );
    assert!(
        generated.contains("server_version = "),
        "generated config is missing server_version: {}",
        generated
    );
    assert!(
        generated.contains("[tls]"),
        "generated config is missing [tls]: {}",
        generated
    );
    assert!(
        generated.contains("server_key = "),
        "generated config is missing tls.server_key: {}",
        generated
    );
    assert!(
        generated.contains("client_public_keys = "),
        "generated config is missing tls.client_public_keys: {}",
        generated
    );
    assert!(
        generated.contains("client_public_keys = []"),
        "generated config should contain empty tls.client_public_keys: {}",
        generated
    );
    let server_key_path = extract_toml_string_value(&generated, "server_key")
        .map(PathBuf::from)
        .expect("generated config should include tls.server_key as string");
    assert!(
        server_key_path.is_absolute(),
        "generated tls.server_key should be absolute: {}",
        server_key_path.display()
    );
    assert!(
        server_key_path.exists(),
        "generated server key file does not exist: {}",
        server_key_path.display()
    );
    let server_key = fs::read_to_string(&server_key_path)?;
    assert!(
        server_key.contains("BEGIN PRIVATE KEY"),
        "generated server key is not PEM private key: {}",
        server_key
    );
    assert!(
        !generated.contains("storage_root = "),
        "generated config unexpectedly contains storage_root: {}",
        generated
    );
    assert!(
        !generated.contains("[runtime]"),
        "generated config unexpectedly contains [runtime]: {}",
        generated
    );

    Ok(())
}

#[test]
#[ignore]
fn e2e_imagod_does_not_overwrite_existing_config() -> TestResult {
    let temp = TempDirBuilder::new()
        .prefix("iecfgo")
        .tempdir_in(std::env::temp_dir())?;
    let config_path = temp.path().join("imagod.toml");
    let key_material = generate_key_material(temp.path())?;
    let storage_root = temp.path().join("s");
    let control_socket_path = temp.path().join("control.sock");
    let server_key = key_material.server_key_path;
    let existing = format!(
        "listen_addr = \"127.0.0.1:0\"\ncontrol_socket_path = \"{}\"\nstorage_root = \"{}\"\nserver_version = \"imagod/existing\"\n\n[tls]\nserver_key = \"{}\"\nclient_public_keys = [\"{}\"]\n",
        toml_escape(control_socket_path.to_string_lossy().as_ref()),
        toml_escape(storage_root.to_string_lossy().as_ref()),
        toml_escape(server_key.to_string_lossy().as_ref()),
        CLIENT_PUBLIC_KEY_SAMPLE,
    );
    fs::write(&config_path, &existing)?;
    let before = fs::read_to_string(&config_path)?;

    let run = run_imagod_until_ready(&config_path, DEFAULT_TIMEOUT, ReadinessMode::Listening)?;
    let after = fs::read_to_string(&config_path)?;

    assert_eq!(
        after,
        before,
        "existing config was overwritten: {}",
        render_run_result(&run)
    );
    assert!(
        !run.combined.contains("imagod created default config at"),
        "unexpected default-config creation log was found: {}",
        render_run_result(&run)
    );
    assert!(
        run.combined.contains("imagod listening on"),
        "startup listen log was not found: {}",
        render_run_result(&run)
    );
    assert!(
        !run.timed_out,
        "imagod startup timed out unexpectedly: {}",
        render_run_result(&run)
    );

    Ok(())
}

fn run_imagod_until_ready(
    config_path: &Path,
    timeout: Duration,
    readiness_mode: ReadinessMode,
) -> TestResult<RunResult> {
    let workspace_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let imagod_binary = resolve_imagod_binary(&workspace_root, "imagod")?;
    let stdout_path = config_path.with_extension("stdout.log");
    let stderr_path = config_path.with_extension("stderr.log");
    let stdout_file = fs::File::create(&stdout_path)?;
    let stderr_file = fs::File::create(&stderr_path)?;

    let mut child = Command::new(imagod_binary)
        .arg("--config")
        .arg(config_path)
        .current_dir(&workspace_root)
        .stdout(Stdio::from(stdout_file))
        .stderr(Stdio::from(stderr_file))
        .spawn()?;
    let timed_out = wait_for_readiness_or_kill(
        &mut child,
        config_path,
        &stdout_path,
        &stderr_path,
        readiness_mode,
        timeout,
    )?;
    let status = child.wait()?;

    let stdout = read_log_file(&stdout_path);
    let stderr = read_log_file(&stderr_path);
    let combined = format!("{stdout}{stderr}");

    Ok(RunResult {
        stdout,
        stderr,
        combined,
        status: status.to_string(),
        timed_out,
    })
}

fn wait_for_readiness_or_kill(
    child: &mut Child,
    config_path: &Path,
    stdout_path: &Path,
    stderr_path: &Path,
    readiness_mode: ReadinessMode,
    timeout: Duration,
) -> TestResult<bool> {
    let deadline = Instant::now() + timeout;
    loop {
        let combined = read_log_file(stdout_path) + &read_log_file(stderr_path);
        if readiness_reached(config_path, &combined, readiness_mode) {
            let _ = child.kill();
            return Ok(false);
        }
        if child.try_wait()?.is_some() {
            return Ok(false);
        }
        if Instant::now() >= deadline {
            let _ = child.kill();
            return Ok(true);
        }
        thread::sleep(Duration::from_millis(100));
    }
}

fn readiness_reached(config_path: &Path, logs: &str, readiness_mode: ReadinessMode) -> bool {
    match readiness_mode {
        ReadinessMode::DefaultConfigCreated => {
            config_path.exists() && logs.contains("imagod created default config at")
        }
        ReadinessMode::Listening => logs.contains("imagod listening on"),
    }
}

fn read_log_file(path: &Path) -> String {
    fs::read_to_string(path).unwrap_or_default()
}

fn render_run_result(run: &RunResult) -> String {
    format!(
        "status={}, timed_out={}, stdout={}, stderr={}",
        run.status, run.timed_out, run.stdout, run.stderr
    )
}

fn toml_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn extract_toml_string_value(content: &str, key: &str) -> Option<String> {
    let prefix = format!("{key} = \"");
    content.lines().find_map(|line| {
        let trimmed = line.trim();
        let rest = trimmed.strip_prefix(&prefix)?;
        let value = rest.strip_suffix('"')?;
        Some(value.replace("\\\\", "\\").replace("\\\"", "\""))
    })
}
