name = "imago-with-python"
main = "cli.wasm"
type = "cli"

[build]
command = "uv run componentize-py -d wit -w wasi:cli/command@0.2.0 componentize main -o cli.wasm"

[capabilities]
wasi = true

[target.default]
remote = "ssh://localhost?socket=/tmp/imagod-componentize-py.sock"
