name = "e2e"
main = "wrong.wasm"
type = "cli"

[[dependencies]]
version = "0.1.0"
kind = "wasm"
wit = "sizumita:ferris"

[[dependencies]]
version = "0.1.0"
kind = "native"
path = "../plugins/imago-node/wit"

[[bindings]]
name = "rpc-greeter"
version = "0.1.0"
path = "wit/rpc-greeter"

[capabilities]
privileged = true
wasi = true
