name = "local-imagod-plugin-hello-app"
main = "target/wasm32-wasip2/release/local-imagod-plugin-hello-app.wasm"
type = "cli"

[build]
command = "CARGO_TARGET_DIR=target cargo build --target wasm32-wasip2 --release"

[[dependencies]]
name = "sizumita:ferris"
version = "0.1.0"
kind = "wasm"
wit = "warg://sizumita:ferris@0.1.0"

[capabilities]
privileged = false

[capabilities.deps]
"sizumita:ferris" = ["sizumita:ferris/says@0.1.0.say"]

[target.default]
remote = "127.0.0.1:4443"
server_name = "localhost"
ca_cert = "certs/ca.crt"
client_cert = "certs/client.crt"
client_key = "certs/client.key"
