listen_addr = "127.0.0.1:4443"
storage_root = ".imagod-data"
server_version = "imagod/local-plugin-hello-example"
compatibility_date = "2026-02-10"

[tls]
server_key = "certs/server.key"
client_public_keys = ["ab5bd390075f66f09862e65a75bb5ebe8a60c7bc138dd0dd21891d91996079e8"]

[runtime]
chunk_size = 1048576
max_inflight_chunks = 16
upload_session_ttl_secs = 900
stop_grace_timeout_secs = 30
runner_ready_timeout_secs = 3
runner_log_buffer_bytes = 262144
epoch_tick_interval_ms = 50
