name = "cli-client"
main = "target/wasm32-wasip2/release/cli-client.wasm"
type = "cli"

[build]
command = "cargo build --target wasm32-wasip2 --release"

[[dependencies]]
version = "0.1.0"
kind = "native"
path = "../../../../plugins/imago-node/wit"

[capabilities]
privileged = false
wasi = true

[capabilities.deps]
"acme:clock" = ["*"]
"imago:node" = ["*"]

[[bindings]]
name = "rpc-greeter"
version = "0.1.0"
path = "../rpc-greeter/wit/world.wit"
