//! Runtime abstraction for runner-side component execution.

use std::{
    collections::BTreeMap,
    path::{Path, PathBuf},
    sync::Arc,
};

use async_trait::async_trait;
use bytes::Bytes;
use imagod_common::ImagodError;
use imagod_ipc::{
    CapabilityPolicy, PluginDependency, ResourceMap, RunnerAppType, RunnerSocketConfig,
    RunnerWasiMount, ServiceBinding, WasiHttpOutboundRule,
};
use tokio::sync::{mpsc, oneshot, watch};

/// Owned run request passed from runner process to runtime implementation.
#[derive(Debug)]
pub struct RuntimeRunRequest {
    /// Component execution model derived from manifest `type`.
    pub app_type: RunnerAppType,
    /// Runner identifier generated by manager.
    pub runner_id: String,
    /// Service name owned by this runner.
    pub service_name: String,
    /// Release hash announced by this runner.
    pub release_hash: String,
    /// Absolute component path.
    pub component_path: PathBuf,
    /// Runtime arguments.
    pub args: Vec<String>,
    /// Runtime environment variables.
    pub envs: BTreeMap<String, String>,
    /// WASI preopened directory mounts.
    pub wasi_mounts: Vec<RunnerWasiMount>,
    /// Allowed outbound rules for `wasi:http` requests.
    pub wasi_http_outbound: Vec<WasiHttpOutboundRule>,
    /// Arbitrary resource policy map available to runtime/native plugins.
    pub resources: ResourceMap,
    /// Socket runtime settings when `app_type=socket`.
    pub socket: Option<RunnerSocketConfig>,
    /// Plugin dependencies resolved from manifest and prepared by manager.
    pub plugin_dependencies: Vec<PluginDependency>,
    /// App-level capability policy used by runtime bridge authorization.
    pub capabilities: CapabilityPolicy,
    /// Allowed outbound bindings for this service.
    pub bindings: Vec<ServiceBinding>,
    /// Manager control socket endpoint used by local RPC bridge calls.
    pub manager_control_endpoint: PathBuf,
    /// Shared secret used to prove manager-authenticated control requests.
    pub manager_auth_secret: String,
    /// Shutdown signal observed by runtime implementation.
    pub shutdown: watch::Receiver<bool>,
    /// Epoch tick interval used for interruption-aware runtimes.
    pub epoch_tick_interval_ms: u64,
    /// Compatibility worker-count value forwarded from manager configuration.
    pub http_worker_count: u32,
    /// Effective HTTP request queue capacity for ingress dispatch.
    pub http_worker_queue_capacity: u32,
    /// Optional signal sent when HTTP runtime initialization has completed.
    pub http_ready_tx: Option<oneshot::Sender<()>>,
}

/// Shared immutable invoke context reused across inbound RPC requests.
#[derive(Debug)]
pub struct RuntimeInvokeContext {
    /// Component execution model derived from manifest `type`.
    pub app_type: RunnerAppType,
    /// Runner identifier generated by manager.
    pub runner_id: String,
    /// Service name owned by this runner.
    pub service_name: String,
    /// Release hash announced by this runner.
    pub release_hash: String,
    /// Absolute component path.
    pub component_path: PathBuf,
    /// Runtime arguments.
    pub args: Vec<String>,
    /// Runtime environment variables.
    pub envs: BTreeMap<String, String>,
    /// WASI preopened directory mounts.
    pub wasi_mounts: Vec<RunnerWasiMount>,
    /// Allowed outbound rules for `wasi:http` requests.
    pub wasi_http_outbound: Vec<WasiHttpOutboundRule>,
    /// Arbitrary resource policy map available to runtime/native plugins.
    pub resources: ResourceMap,
    /// Plugin dependencies resolved from manifest and prepared by manager.
    pub plugin_dependencies: Vec<PluginDependency>,
    /// App-level capability policy used by runtime bridge authorization.
    pub capabilities: CapabilityPolicy,
    /// Allowed outbound bindings for this service.
    pub bindings: Vec<ServiceBinding>,
    /// Manager control socket endpoint used by local RPC bridge calls.
    pub manager_control_endpoint: PathBuf,
    /// Shared secret used to prove manager-authenticated control requests.
    pub manager_auth_secret: String,
}

/// Owned invoke request passed from runner inbound control path to runtime implementation.
#[derive(Debug)]
pub struct RuntimeInvokeRequest {
    /// Shared immutable context for this runner.
    pub context: Arc<RuntimeInvokeContext>,
    /// Target interface identifier.
    pub interface_id: String,
    /// Target function name.
    pub function: String,
    /// CBOR-encoded invocation payload.
    pub payload_cbor: Vec<u8>,
}

/// Invocation runtime abstraction for runner inbound dispatch.
#[async_trait]
pub trait RuntimeInvoker: Send + Sync {
    /// Executes one RPC invocation against the component.
    async fn invoke_component(&self, request: RuntimeInvokeRequest)
    -> Result<Vec<u8>, ImagodError>;
}

/// Runtime-agnostic HTTP request model passed from ingress to wasm runtime.
#[derive(Debug, Clone)]
pub struct RuntimeHttpRequest {
    /// Upper-case HTTP method (e.g. `GET`).
    pub method: String,
    /// Request URI as received by ingress (path or absolute URI).
    pub uri: String,
    /// HTTP headers represented as raw bytes.
    pub headers: Vec<(String, Vec<u8>)>,
    /// Entire request body.
    pub body: Vec<u8>,
}

/// Runtime-agnostic HTTP response model returned from wasm runtime.
#[derive(Debug, Clone)]
pub struct RuntimeHttpResponse {
    /// HTTP status code.
    pub status: u16,
    /// HTTP headers represented as raw bytes.
    pub headers: Vec<(String, Vec<u8>)>,
    /// Entire response body as a shareable byte buffer.
    pub body: Bytes,
}

/// Runtime abstraction so runner can swap out concrete wasm engines.
#[async_trait]
pub trait ComponentRuntime: Send + Sync {
    /// Validates that the component can be loaded by this runtime.
    fn validate_component(&self, component_path: &Path) -> Result<(), ImagodError>;

    /// Executes one component until completion or shutdown.
    async fn run_component(&self, request: RuntimeRunRequest) -> Result<(), ImagodError>;

    /// Handles one HTTP request using the already-running HTTP component.
    async fn handle_http_request(
        &self,
        request: RuntimeHttpRequest,
    ) -> Result<RuntimeHttpResponse, ImagodError>;
}

/// Runtime-facing item sent to HTTP worker tasks.
#[derive(Debug)]
pub struct RuntimeHttpWorkItem {
    /// Incoming HTTP request forwarded from ingress.
    pub request: RuntimeHttpRequest,
    /// One-shot sender used by runtime worker to complete the response.
    pub response_tx: oneshot::Sender<Result<RuntimeHttpResponse, ImagodError>>,
}

/// Supervises lifecycle of an HTTP component request channel.
#[async_trait]
pub trait HttpComponentSupervisor: Send + Sync {
    /// Registers the active HTTP worker sender.
    async fn register_http_component(
        &self,
        request_tx: mpsc::Sender<RuntimeHttpWorkItem>,
        http_ready_tx: Option<oneshot::Sender<()>>,
    ) -> Result<(), ImagodError>;

    /// Returns the active HTTP worker sender.
    async fn request_sender(&self) -> Result<mpsc::Sender<RuntimeHttpWorkItem>, ImagodError>;

    /// Unregisters and returns the active HTTP worker sender.
    async fn unregister_http_component(&self) -> Option<mpsc::Sender<RuntimeHttpWorkItem>>;
}

/// Resolved provider for one plugin import namespace.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PluginImportProvider {
    /// Import is satisfied by the current component instance exports.
    SelfComponent,
    /// Import is satisfied by another dependency package.
    Dependency(String),
}

/// String-based component interface metadata used for dependency planning.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PluginComponentInterfaces {
    /// Non-WASI instance import names.
    pub imports: Vec<String>,
    /// Exported instance interface names.
    pub exports: std::collections::BTreeSet<String>,
}

/// Resolves dependency order and import providers for plugin wiring.
pub trait PluginResolver: Send + Sync {
    /// Returns the explicit dependency package names.
    fn all_dependency_names(
        &self,
        dependencies: &[PluginDependency],
    ) -> std::collections::BTreeSet<String>;

    /// Calculates dependency instantiation order.
    fn dependency_topological_order(
        &self,
        dependencies: &[PluginDependency],
        component_interfaces_by_dependency: &BTreeMap<String, PluginComponentInterfaces>,
    ) -> Result<Vec<usize>, ImagodError>;

    /// Resolves provider for one import namespace.
    fn resolve_import_provider(
        &self,
        caller_name: &str,
        import_name: &str,
        self_export_interfaces: &std::collections::BTreeSet<String>,
        explicit_dependency_names: &std::collections::BTreeSet<String>,
        available_dependency_names: &std::collections::BTreeSet<String>,
        allow_self_provider: bool,
    ) -> Result<PluginImportProvider, ImagodError>;
}

/// Capability policy checks used by runtime plugin and WASI bridges.
pub trait CapabilityChecker: Send + Sync {
    /// Returns whether one dependency function call is allowed.
    fn is_dependency_function_allowed(
        &self,
        policy: &CapabilityPolicy,
        dependency_name: &str,
        interface_name: &str,
        function_name: &str,
    ) -> bool;

    /// Ensures one dependency function call is allowed.
    fn ensure_dependency_function_allowed(
        &self,
        caller_name: &str,
        policy: &CapabilityPolicy,
        dependency_name: &str,
        interface_name: &str,
        function_name: &str,
    ) -> Result<(), ImagodError>;

    /// Returns whether one WASI function call is allowed.
    fn is_wasi_function_allowed(
        &self,
        policy: &CapabilityPolicy,
        interface_name: &str,
        function_name: &str,
    ) -> bool;

    /// Ensures one WASI function call is allowed.
    fn ensure_wasi_function_allowed(
        &self,
        caller_name: &str,
        policy: &CapabilityPolicy,
        interface_name: &str,
        function_name: &str,
    ) -> Result<(), ImagodError>;
}
