[[compose.devstack.services]]
imago = "services/rpc-greeter/imago.toml"

[[compose.devstack.services]]
imago = "services/cli-client/imago.toml"

[[compose.prepare.services]]
imago = "services/rpc-greeter/imago.toml"

[profile.dev]
config = "devstack"

[profile.prepare]
config = "prepare"

[target.default]
remote = "ssh://localhost?socket=/tmp/imagod-compose-bindings.sock"
