name: nanokvm-build
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: imago-nanokvm-runner-set
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add PATH
        run: echo "/home/runner/riscv64-unknown-linux-musl/bin" >> "$GITHUB_PATH"

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install target
        run: rustup target add riscv64gc-unknown-linux-musl

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --bin imago-nanokvm -F host-nanokvm -F plugins/nanokvm --target riscv64gc-unknown-linux-musl

      - name: Upload Imago
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: 'error'
          name: imago-${{ steps.checkout.outputs.commit }}
          path: target/riscv64gc-unknown-linux-musl/release/imago-nanokvm
          retention-days: 12
