name: nanokvm-build
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: imago-nanokvm-runner-set
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Add PATH
        run: echo "/home/runner/riscv64-unknown-linux-musl/bin" >> "$GITHUB_PATH"

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install target
        run: rustup target add riscv64gc-unknown-linux-musl

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --locked --release --bin imagod --target riscv64gc-unknown-linux-musl

      - name: Upload Imago
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          name: imago-${{ github.sha }}
          path: target/riscv64gc-unknown-linux-musl/release/imagod
          retention-days: 12
